# This is a basic workflow to help you get started with Actions

name: Demo Keploy CI/CD Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  keploy_test_case:
    runs-on: ubuntu-latest
    steps:
      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash
      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=dca185d2-96b2-4e04-814e-3c2342a585ff --base-path https://petclinic-hosted.keploy.io/ --cloud
